#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 19 23:48:25 2019

@author: shivam
"""

import pickle
import pandas as pd
from wordcloud import WordCloud
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image

with open('data_dtm_clean_1.pkl', 'rb') as pickle_file:
    data_dtm = pickle.load(pickle_file)
    
# convert it to data frame
data_dtm = pd.DataFrame(data_dtm)

# Find words which used more frequently
words = pd.DataFrame({'words': data_dtm.columns, 'freq': data_dtm.iloc[0, :]})

# sort the freq of words in decreasing order
words = words.sort_values('freq', ascending=False)

with open('speech_data_clean_1.pkl', 'rb') as pickle_file:
    text = pickle.load(pickle_file)

modi_mask = np.array(Image.open("mask.png"))

modi_mask_2 = np.array(Image.open("modi_mask.png"))

# Plot wordcloud 
wordcloud = WordCloud(width=300, height=300,max_font_size=50, max_words=100, 
                      background_color="white", mask=modi_mask, 
                      contour_color='black', contour_width=3).generate(text.iloc[1, 0])

plt.figure()
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.show()

wordcloud.to_file("wordcloud_modi.png")
